name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use ONE Node version (20) for everything
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend
      - name: Install backend deps
        working-directory: ./backend
        run: npm install

      # Frontend
      - name: Install frontend deps & build
        working-directory: ./frontend
        run: |
          npm install
          npm run build